# Generated by Django 3.0.7 on 2020-08-06 00:11

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0003_remove_profile_ratings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Like",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "liker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="liker", to="user.Profile"
                    ),
                ),
            ],
            options={"unique_together": {("liker", "comment_id")}},
        ),
    ]
