# Generated by Django 3.0.6 on 2021-01-29 22:48

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0001_initial"),
        ("lst", "0002_lst_num_likes"),
        ("like", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="like_type",
            field=models.CharField(
                choices=[("comment_like", "Comment Like"), ("list_like", "List Like")],
                default="comment_like",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="lst",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="likers", to="lst.Lst"
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likers",
                to="comment.Comment",
            ),
        ),
    ]
