# Generated by Django 3.0.7 on 2020-09-05 18:34

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("like", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="liker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="likes", to="user.Profile"
            ),
        ),
        migrations.AlterUniqueTogether(name="like", unique_together={("liker", "comment")},),
    ]
