# Generated by Django 3.0.7 on 2020-08-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("like", "0003_auto_20200807_0343"),
    ]

    operations = [
        migrations.AlterModelOptions(name="like", options={"ordering": ["-created_at"]},),
    ]
