# Generated by Django 3.1.5 on 2021-02-20 06:39

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("suggestion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatesuggestion",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="suggestions_received", to="user.profile"
            ),
        ),
    ]
