# Generated by Django 3.1.5 on 2021-02-20 07:05

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("suggestion", "0002_auto_20210220_0639"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatesuggestion",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggestions_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
