# Generated by Django 3.1.5 on 2021-03-06 02:43

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("asset", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("consumer", "Consumer"), ("staff", "Staff")], default="consumer", max_length=8
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("profile_pic", models.TextField(blank=True, null=True)),
                ("phone_number", models.TextField(blank=True, null=True)),
                ("social_id", models.TextField(blank=True, null=True)),
                ("social_id_token_type", models.TextField(blank=True, null=True)),
                ("social_id_token", models.TextField(blank=True, null=True)),
                ("notif_time_viewed", models.DateTimeField(blank=True, null=True)),
                ("suggest_time_viewed", models.DateTimeField(blank=True, null=True)),
                (
                    "profile_asset_bundle",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="asset.assetbundle"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
