# Generated by Django 3.1.5 on 2022-03-12 08:46

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0002_profile_profile_pic_url"),
        ("reaction", "0007_reaction_num_likes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Thought",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("num_likes", models.IntegerField(default=0, null=True)),
                ("text", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="thought", to="user.profile"
                    ),
                ),
                (
                    "reaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="thoughts", to="reaction.reaction"
                    ),
                ),
            ],
            options={"ordering": ["-num_likes"]},
        ),
    ]
