# Generated by Django 3.1.5 on 2021-02-22 22:34

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
        ("lst", "0001_initial"),
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Like",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "like_type",
                    models.CharField(
                        choices=[("comment_like", "Comment Like"), ("list_like", "List Like")],
                        default="comment_like",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likers",
                        to="comment.comment",
                    ),
                ),
                (
                    "liker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="likes", to="user.profile"
                    ),
                ),
                (
                    "lst",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likers",
                        to="lst.lst",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"], "unique_together": {("liker", "comment")}},
        ),
    ]
