# Generated by Django 3.1.5 on 2022-03-12 08:46

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("like", "0002_like_reaction"),
        ("thought", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="thought",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likers",
                to="thought.thought",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="like_type",
            field=models.CharField(
                choices=[
                    ("comment_like", "Comment Like"),
                    ("list_like", "List Like"),
                    ("suggestion_like", "Suggestion Like"),
                    ("reaction_like", "Reaction Like"),
                    ("thought_like", "Thought Like"),
                ],
                default="comment_like",
                max_length=50,
            ),
        ),
        migrations.AlterUniqueTogether(name="like", unique_together=set(),),
    ]
