# Generated by Django 3.1.5 on 2021-02-20 06:39

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("suggestion", "0001_initial"),
        ("like", "0002_auto_20210129_2248"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="suggestion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likers",
                to="suggestion.privatesuggestion",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="like_type",
            field=models.CharField(
                choices=[
                    ("comment_like", "Comment Like"),
                    ("list_like", "List Like"),
                    ("suggestion_like", "Suggestion Like"),
                ],
                default="comment_like",
                max_length=50,
            ),
        ),
    ]
