# Generated by Django 3.1.5 on 2021-02-20 07:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("like", "0003_auto_20210220_0639"),
    ]

    operations = [
        migrations.RemoveField(model_name="like", name="suggestion",),
        migrations.AlterField(
            model_name="like",
            name="like_type",
            field=models.CharField(
                choices=[("comment_like", "Comment Like"), ("list_like", "List Like")],
                default="comment_like",
                max_length=50,
            ),
        ),
    ]
