# Generated by Django 3.0.6 on 2020-05-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='kind',
            field=models.CharField(choices=[('original', 'Original'), ('large', 'Large'), ('small', 'Small')], default='http://s3.com/uploads/', max_length=8),
        ),
    ]
