# Generated by Django 3.0.6 on 2020-05-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("asset", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="asset", name="is_processing", field=models.BooleanField(default=False), preserve_default=False,
        )
    ]
