language: python # => 1

python: # => 2
    - "3.7"
# services: # => 3
#     - postgresql

env: # => 4
    - DEBUG=True
    - SQLITE3=True
    - TMDB_API_KEY=''
    - SECRET_KEY=''
    - DJANGO_ALLOWED_HOSTS=localhost
    - VALIDATE_SOCIAL_TOKEN=False
    - APPLE_PRIVATE_KEY=''
    - APNS_CERTIFICATE=''
    - FCM_API_KEY=''
install: # => 5
    - pip install -r /src/flick/requirements.txt

# before_script: # => 6
#     - mysql -e 'create database test;' -u root
script: # => 7
    - python manage.py test --exclude-tag=flakey
