# Generated by Django 3.0.6 on 2020-05-30 22:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("item", "0001_initial")]

    operations = [migrations.AlterUniqueTogether(name="like", unique_together={("item", "owner")})]
