version: "3.4"

services:
    app:
        command: sh -c "./wait-for-it.sh postgres:5432 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        volumes:
            - .:/usr/src/app
