version: "3.4"

services:
    app:
        environment:
            - DJANGO_SETTINGS_MODULE=flick.settings.production
            - SECRET_KEY
        volumes:
            - static:/static

    nginx:
        container_name: nginx
        command: wait-for-it.sh app:8000 -- nginx -g "daemon off;"
        depends_on:
            - app
        image: nginx:alpine
        networks:
            - main
        ports:
            - "80:80"
        restart: on-failure
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./wait-for-it.sh:/bin/wait-for-it.sh
            - static:/var/www/app/static

volumes:
    static:
