version: "3.4"

services:
    redis:
        container_name: redis
        hostname: redis
        image: redis:latest
        networks:
            - main
        ports:
            - "6379:6379"
        restart: on-failure

    postgres:
        container_name: postgres
        hostname: postgres
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        networks:
            - main
        ports:
            - "5432:5432"
        restart: on-failure
        volumes:
            - postgresql-data:/var/lib/postgresql/data

    app:
        build: .
        # command:
        #     [
        #         "/wait-for-it.sh",
        #         "postgres:5432",
        #         "&&",
        #         "python",
        #         "manage.py",
        #         "migrate",
        #         "&&",
        #         "gunicorn",
        #         "flick.wsgi",
        #         "-b",
        #         "0.0.0.0:8000",
        #     ]
        command: sh -c "bash wait-for-it.sh postgres:5432 && python manage.py collectstatic --no-input && python manage.py migrate && gunicorn flick.wsgi -b 0.0.0.0:8000"
        container_name: app
        depends_on:
            - postgres
            - redis
        expose:
            - "8000"
        hostname: app
        image: app-image
        networks:
            - main
        restart: on-failure
        # volumes:
        #     - ./wait-for-it.sh:/usr/bin/wait-for-it.sh

    celery_worker:
        command: sh -c "./wait-for-it.sh redis:6379 && ./wait-for-it.sh app:8000 -- celery -A flick worker -l info"
        depends_on:
            - app
            - postgres
            - redis
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
            resources:
                limits:
                    cpus: "0.50"
                    memory: 50M
                reservations:
                    cpus: "0.25"
                    memory: 20M
        hostname: celery_worker
        image: app-image
        networks:
            - main
        restart: on-failure
        # volumes:
        #     - ./wait-for-it.sh:/usr/bin/wait-for-it.sh

networks:
    main:

volumes:
    postgresql-data:
