# Generated by Django 3.0.7 on 2020-08-14 03:14

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatesuggestion", name="created_at", field=models.DateTimeField(auto_now=True),
        ),
    ]
