# Generated by Django 3.0.7 on 2020-09-05 18:34

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0001_initial"),
        ("suggestion", "0001_initial"),
        ("show", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicsuggestion",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="suggestions_posted", to="user.Profile"
            ),
        ),
        migrations.AddField(
            model_name="publicsuggestion",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="suggestion_post", to="show.Show"
            ),
        ),
        migrations.AddField(
            model_name="privatesuggestion",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="suggestions_sent", to="user.Profile"
            ),
        ),
        migrations.AddField(
            model_name="privatesuggestion",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="suggestion", to="show.Show"
            ),
        ),
        migrations.AddField(
            model_name="privatesuggestion",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggestions_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="privatesuggestion", unique_together={("message", "show", "from_user", "to_user")},
        ),
    ]
