# Generated by Django 3.0.7 on 2020-08-15 19:35

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("show", "0006_auto_20200802_0723"),
        ("user", "0003_remove_profile_ratings"),
        ("suggestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatesuggestion", name="created_at", field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="PublicSuggestion",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.CharField(blank=True, max_length=140)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggestions_posted",
                        to="user.Profile",
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="suggestion_post", to="show.Show"
                    ),
                ),
            ],
        ),
    ]
