# Generated by Django 3.0.6 on 2021-01-10 08:41

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestion", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="privatesuggestion",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddField(
            model_name="privatesuggestion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="publicsuggestion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="privatesuggestion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="publicsuggestion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
