# Generated by Django 3.0.7 on 2020-08-16 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suggestion", "0003_auto_20200815_1940"),
    ]

    operations = [
        migrations.AlterModelOptions(name="privatesuggestion", options={"ordering": ["created_at"]},),
    ]
