# Generated by Django 3.0.7 on 2020-08-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suggestion", "0004_auto_20200816_0726"),
    ]

    operations = [
        migrations.AlterModelOptions(name="privatesuggestion", options={"ordering": ["-created_at"]},),
    ]
