# Generated by Django 3.0.6 on 2020-08-21 18:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("suggestion", "0005_auto_20200816_0739")]

    operations = [
        migrations.AlterField(
            model_name="privatesuggestion",
            name="message",
            field=models.CharField(blank=True, max_length=140, null=True),
        )
    ]
