# Generated by Django 3.0.6 on 2020-08-21 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("suggestion", "0006_auto_20200821_1856"), ("suggestion", "0006_auto_20200818_2342")]

    operations = []
