# Generated by Django 3.0.7 on 2020-08-02 20:15

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_profile_ratings"),
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="comment", old_name="text", new_name="message",),
        migrations.AlterField(
            model_name="comment",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="owner", to="user.Profile"
            ),
        ),
        migrations.AlterUniqueTogether(name="comment", unique_together={("owner", "message", "is_spoiler")},),
    ]
