# Generated by Django 3.0.7 on 2020-09-05 18:34

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
        ("comment", "0001_initial"),
        ("show", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="comment", to="user.Profile"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="show",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="show.Show"
            ),
        ),
        migrations.AlterUniqueTogether(name="comment", unique_together={("owner", "message", "is_spoiler", "show")},),
    ]
