# Generated by Django 3.0.7 on 2020-08-02 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_profile_ratings"),
        ("show", "0006_auto_20200802_0723"),
        ("comment", "0002_auto_20200802_2015"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="comment", unique_together={("owner", "message", "is_spoiler", "show")},),
    ]
