# Generated by Django 3.0.6 on 2021-01-20 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_profile_suggest_time_viewed"),
        ("show", "0006_show_animelist_rank"),
        ("comment", "0002_auto_20210116_2359"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="comment", unique_together={("owner", "is_spoiler", "show")},),
    ]
