# Generated by Django 3.0.7 on 2020-09-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0002_auto_20200905_1834"),
    ]

    operations = [
        migrations.AlterModelOptions(name="comment", options={"ordering": ["created_at"]},),
    ]
