# Generated by Django 3.0.6 on 2021-01-20 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0003_auto_20210120_0302"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="comment", unique_together=set(),),
    ]
