# Generated by Django 3.0.7 on 2020-08-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0004_auto_20200803_0545"),
    ]

    operations = [
        migrations.AlterModelOptions(name="comment", options={"ordering": ["-created_at"]},),
    ]
