# Generated by Django 3.0.6 on 2020-07-25 19:15

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("show", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.PositiveIntegerField(blank=True, null=True)),
                ("show", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="show.Show")),
            ],
        )
    ]
