# Generated by Django 3.0.6 on 2020-07-25 19:30

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("user", "0003_remove_profile_ratings"), ("rating", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="rating", name="show"),
        migrations.AddField(
            model_name="rating",
            name="rater",
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to="user.Profile"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rating", name="score", field=models.PositiveIntegerField(blank=True, default=None, null=True)
        ),
    ]
