# Generated by Django 3.0.6 on 2020-07-26 03:57

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("rating", "0002_auto_20200725_1930")]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rater",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        )
    ]
