# Generated by Django 3.0.6 on 2020-08-02 18:03

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("rating", "0003_auto_20200726_0357")]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rater",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        )
    ]
