# Generated by Django 3.0.6 on 2020-07-11 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("show", "0001_initial"), ("user", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Lst",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lst_name", models.CharField(max_length=100)),
                ("lst_pic", models.TextField(blank=True, null=True)),
                ("is_saved", models.BooleanField(default=False, null=True)),
                ("is_private", models.BooleanField(default=False, null=True)),
                ("is_watch_later", models.BooleanField(default=False, null=True)),
                ("collaborators", models.ManyToManyField(blank=True, related_name="collab_lsts", to="user.Profile")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="owner_lsts", to="user.Profile"
                    ),
                ),
                ("shows", models.ManyToManyField(blank=True, to="show.Show")),
            ],
        )
    ]
