# Generated by Django 3.0.6 on 2020-05-31 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("show", "0002_auto_20200531_0027"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("asset", "0002_asset_is_processing"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lst",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_favorite", models.BooleanField()),
                ("is_private", models.BooleanField()),
                ("is_watched", models.BooleanField()),
                ("collaborators", models.ManyToManyField(related_name="collaborators", to=settings.AUTH_USER_MODEL)),
                ("lst_name", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="asset.AssetBundle")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="owner", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("shows", models.ManyToManyField(to="show.Show")),
            ],
        )
    ]
