# Generated by Django 3.0.6 on 2020-05-31 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("asset", "0002_asset_is_processing"),
        ("show", "0003_auto_20200531_0040"),
        ("lst", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lst",
            name="lst_pic",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="asset.AssetBundle"
            ),
        ),
        migrations.AlterField(
            model_name="lst",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="collaborators", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(model_name="lst", name="is_favorite", field=models.BooleanField(default=False)),
        migrations.AlterField(model_name="lst", name="is_private", field=models.BooleanField(default=False)),
        migrations.AlterField(model_name="lst", name="is_watched", field=models.BooleanField(default=False)),
        migrations.AlterField(model_name="lst", name="lst_name", field=models.CharField(max_length=100)),
        migrations.AlterField(
            model_name="lst", name="shows", field=models.ManyToManyField(blank=True, null=True, to="show.Show")
        ),
    ]
