# Generated by Django 3.0.7 on 2020-09-05 18:34

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lst", "0001_initial"),
        ("user", "0001_initial"),
        ("tag", "0001_initial"),
        ("show", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lst",
            name="collaborators",
            field=models.ManyToManyField(blank=True, related_name="collab_lsts", to="user.Profile"),
        ),
        migrations.AddField(
            model_name="lst",
            name="custom_tags",
            field=models.ManyToManyField(blank=True, related_name="lsts", to="tag.Tag"),
        ),
        migrations.AddField(
            model_name="lst",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="owner_lsts", to="user.Profile"
            ),
        ),
        migrations.AddField(model_name="lst", name="shows", field=models.ManyToManyField(blank=True, to="show.Show"),),
    ]
