# Generated by Django 3.0.6 on 2020-07-12 17:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("tag", "0001_initial"), ("lst", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="lst",
            name="custom_tags",
            field=models.ManyToManyField(blank=True, related_name="lsts", to="tag.Tag"),
        )
    ]
