# Generated by Django 3.0.6 on 2021-01-17 03:43

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("lst", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lst",
            name="description",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
