# Generated by Django 3.0.6 on 2021-01-20 19:39

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("lst", "0002_lst_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lst",
            name="description",
            field=models.CharField(blank=True, default="", max_length=150, null=True),
        ),
    ]
