# Generated by Django 3.0.6 on 2020-08-16 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("lst", "0002_lst_custom_tags")]

    operations = [
        migrations.RenameField(model_name="lst", old_name="lst_name", new_name="name"),
        migrations.RenameField(model_name="lst", old_name="lst_pic", new_name="pic"),
    ]
