# Generated by Django 3.0.6 on 2020-06-22 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("lst", "0004_auto_20200621_2340")]

    operations = [migrations.RenameField(model_name="lst", old_name="collaborator", new_name="collaborators")]
