# Generated by Django 3.0.6 on 2020-06-27 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("show", "0010_auto_20200615_0252"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lst", "0005_auto_20200622_0057"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lst",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="collaborator", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(model_name="lst", name="lst_pic", field=models.TextField(blank=True, null=True)),
        migrations.AlterField(
            model_name="lst", name="shows", field=models.ManyToManyField(blank=True, null=True, to="show.Show")
        ),
    ]
