# Generated by Django 3.0.6 on 2020-06-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("lst", "0006_auto_20200627_1946")]

    operations = [
        migrations.AlterField(
            model_name="lst", name="is_favorite", field=models.BooleanField(default=False, null=True)
        ),
        migrations.AlterField(model_name="lst", name="is_private", field=models.BooleanField(default=False, null=True)),
        migrations.AlterField(model_name="lst", name="is_watched", field=models.BooleanField(default=False, null=True)),
    ]
