# Generated by Django 3.0.6 on 2020-06-27 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("lst", "0007_auto_20200627_1947")]

    operations = [
        migrations.AlterField(
            model_name="lst",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="collab_lsts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="lst",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="owner_lsts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
