# Generated by Django 3.0.6 on 2021-01-26 00:16

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0001_initial"),
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification",
                to="comment.Comment",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("list_invite", "List Invite"),
                    ("list_edit", "List Edit"),
                    ("incoming_friend_request_accepted", "Incoming Friend Request Accepted"),
                    ("outgoing_friend_request_accepted", "Outoing Friend Request Accepted"),
                    ("comment_like", "comment_like"),
                ],
                default=None,
                max_length=50,
            ),
        ),
    ]
