# Generated by Django 3.1.5 on 2021-03-05 23:52

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notification", "0001_initial"),
        ("user", "0001_initial"),
        ("suggestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="suggestion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification",
                to="suggestion.privatesuggestion",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="to_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_notification",
                to="user.profile",
            ),
        ),
    ]
