# Generated by Django 3.0.6 on 2021-01-26 00:42

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_auto_20210126_0016"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("list_invite", "List Invite"),
                    ("list_edit", "List Edit"),
                    ("incoming_friend_request_accepted", "Incoming Friend Request Accepted"),
                    ("outgoing_friend_request_accepted", "Outoing Friend Request Accepted"),
                    ("comment_like", "Comment Like"),
                ],
                default=None,
                max_length=50,
            ),
        ),
    ]
