# Generated by Django 3.1.5 on 2021-02-20 07:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0006_auto_20210220_0639"),
    ]

    operations = [
        migrations.RemoveField(model_name="notification", name="suggestion",),
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("list_invite", "List Invite"),
                    ("list_edit", "List Edit"),
                    ("incoming_friend_request_accepted", "Incoming Friend Request Accepted"),
                    ("outgoing_friend_request_accepted", "Outoing Friend Request Accepted"),
                    ("comment_like", "Comment Like"),
                    ("list_like", "List Like"),
                    ("group_invite", "Group Invite"),
                ],
                default=None,
                max_length=50,
            ),
        ),
    ]
