# Generated by Django 3.1.5 on 2021-02-22 22:34

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comment", "0001_initial"),
        ("discover_recommend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discover",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "friend_comments",
                    models.ManyToManyField(blank=True, related_name="friend_comment", to="comment.Comment"),
                ),
                (
                    "friend_recommendations",
                    models.ManyToManyField(blank=True, related_name="profile_recommend", to="user.Profile"),
                ),
                (
                    "list_recommendations",
                    models.ManyToManyField(
                        blank=True, related_name="list_recommend", to="discover_recommend.DiscoverRecommendation"
                    ),
                ),
                (
                    "show_recommendations",
                    models.ManyToManyField(
                        blank=True, related_name="show_recommend", to="discover_recommend.DiscoverRecommendation"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
