# Generated by Django 3.0.6 on 2021-02-20 22:07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comment", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discover",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "friend_comments",
                    models.ManyToManyField(blank=True, related_name="friend_comment", to="comment.Comment"),
                ),
                (
                    "friend_recommendations",
                    models.ManyToManyField(blank=True, related_name="profile_recommend", to="user.Profile"),
                ),
            ],
        ),
    ]
