# Generated by Django 3.1.5 on 2021-03-05 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discover", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="discover", name="trending_lsts",),
        migrations.RemoveField(model_name="discover", name="trending_shows",),
    ]
