# Generated by Django 3.2.11 on 2022-02-19 23:20

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reaction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reaction",
            name="visibility",
            field=models.CharField(choices=[("P", "Public"), ("F", "Friends")], default="P", max_length=20),
        ),
    ]
