# Generated by Django 3.2.11 on 2022-02-19 23:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reaction", "0003_alter_reaction_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="visibility",
            field=models.CharField(
                choices=[("public", "public"), ("friends", "friends")], default="public", max_length=20
            ),
        ),
    ]
