# Generated by Django 3.2.11 on 2022-03-03 18:24

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reaction", "0004_alter_reaction_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="visibility",
            field=models.CharField(choices=[("public", "p"), ("friends", "f")], default="public", max_length=20),
        ),
    ]
