# Generated by Django 3.1.5 on 2022-03-15 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reaction", "0007_reaction_num_likes"),
        ("reaction", "0007_auto_20220314_0103"),
    ]

    operations = []
