# Generated by Django 3.1.5 on 2021-06-08 21:12

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="is_processing",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="kind",
        ),
        migrations.AlterField(
            model_name="assetbundle",
            name="base_url",
            field=models.CharField(max_length=255),
        ),
    ]
