# Generated by Django 3.0.6 on 2020-08-08 20:28

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("user", "0003_remove_profile_ratings"), ("lst", "0002_lst_custom_tags")]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "notif_type",
                    models.CharField(
                        choices=[("list_invite", "List Invite"), ("list_edit", "List Edit")],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("num_shows_added", models.IntegerField(blank=True, null=True)),
                ("num_shows_removed", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collaborator_added",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lst_added_to",
                        to="user.Profile",
                    ),
                ),
                (
                    "collaborator_removed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lst_removed_from",
                        to="user.Profile",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notification",
                        to="user.Profile",
                    ),
                ),
                (
                    "lst",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification",
                        to="lst.Lst",
                    ),
                ),
            ],
            options={"ordering": ["created_at"]},
        )
    ]
