# Generated by Django 3.0.6 on 2021-01-09 19:22

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
        ("lst", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "notif_type",
                    models.CharField(
                        choices=[
                            ("list_invite", "List Invite"),
                            ("list_edit", "List Edit"),
                            ("friend_request", "Friend Request"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("num_shows_added", models.IntegerField(blank=True, null=True)),
                ("num_shows_removed", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("friend_request_accepted", models.BooleanField(blank=True, null=True)),
                (
                    "collaborators_added",
                    models.ManyToManyField(blank=True, related_name="added_to_lst_notification", to="user.Profile"),
                ),
                (
                    "collaborators_removed",
                    models.ManyToManyField(blank=True, related_name="removed_from_lst_notification", to="user.Profile"),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notification",
                        to="user.Profile",
                    ),
                ),
                (
                    "lst",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification",
                        to="lst.Lst",
                    ),
                ),
                (
                    "new_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newly_owned_lst_notification",
                        to="user.Profile",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_notification",
                        to="user.Profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
