# Generated by Django 3.0.7 on 2020-09-05 18:34

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "notif_type",
                    models.CharField(
                        choices=[
                            ("list_invite", "List Invite"),
                            ("list_edit", "List Edit"),
                            ("friend_request", "Friend Request"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                ("num_shows_added", models.IntegerField(blank=True, null=True)),
                ("num_shows_removed", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("friend_request_accepted", models.BooleanField(blank=True, null=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
