# Generated by Django 3.0.6 on 2021-01-10 02:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="has_viewed",
            field=models.BooleanField(default=False),
        ),
    ]
