# Generated by Django 3.0.6 on 2020-08-09 23:02

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("user", "0003_remove_profile_ratings"), ("notification", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="to_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_notification",
                to="user.Profile",
            ),
        )
    ]
