# Generated by Django 3.0.6 on 2021-01-10 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_notification_has_viewed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="has_viewed",
        ),
    ]
