# Generated by Django 3.0.6 on 2020-08-19 00:24

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("notification", "0004_auto_20200818_2342")]

    operations = [
        migrations.AddField(
            model_name="notification", name="friend_request_accepted", field=models.BooleanField(blank=True, null=True)
        ),
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("list_invite", "List Invite"),
                    ("list_edit", "List Edit"),
                    ("friend_request", "Friend Request"),
                ],
                default=None,
                max_length=20,
            ),
        ),
    ]
