# Generated by Django 3.0.6 on 2021-01-15 20:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0004_auto_20210110_2122"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="friend_request_accepted",
            new_name="incoming_friend_request_accepted",
        ),
        migrations.AddField(
            model_name="notification",
            name="outgoing_friend_request_accepted",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("list_invite", "List Invite"),
                    ("list_edit", "List Edit"),
                    ("incoming_friend_request_accepted", "Incoming Friend Request Accepted"),
                    ("outgoing_friend_request_accepted", "Outoing Friend Request Accepted"),
                ],
                default=None,
                max_length=50,
            ),
        ),
    ]
