# Generated by Django 3.0.6 on 2021-01-15 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0005_auto_20210115_2005"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="incoming_friend_request_accepted",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="outgoing_friend_request_accepted",
        ),
    ]
