# Generated by Django 3.0.6 on 2020-08-21 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("notification", "0004_auto_20200821_1856"), ("notification", "0005_auto_20200819_0024")]

    operations = []
