# Generated by Django 3.0.6 on 2020-08-24 23:41

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("user", "0003_remove_profile_ratings"), ("notification", "0006_merge_20200821_1900")]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="new_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newly_owned_lst_notification",
                to="user.Profile",
            ),
        )
    ]
