# Generated by Django 3.0.6 on 2020-08-26 20:33

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("user", "0003_remove_profile_ratings"), ("notification", "0008_auto_20200826_2033")]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="collaborators_added",
            field=models.ManyToManyField(blank=True, related_name="added_to_lst_notification", to="user.Profile"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="collaborators_removed",
            field=models.ManyToManyField(blank=True, related_name="removed_from_lst_notification", to="user.Profile"),
        ),
    ]
