# Generated by Django 3.0.6 on 2020-08-27 01:07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("notification", "0009_auto_20200826_2033")]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="num_shows_added",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="num_shows_removed",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
