# Generated by Django 3.0.6 on 2020-08-27 01:09

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("notification", "0010_auto_20200827_0107")]

    operations = [
        migrations.AlterField(
            model_name="notification", name="num_shows_added", field=models.IntegerField(blank=True, null=True)
        ),
        migrations.AlterField(
            model_name="notification", name="num_shows_removed", field=models.IntegerField(blank=True, null=True)
        ),
    ]
