# Generated by Django 3.1.5 on 2021-02-22 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lst", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="lst", options={"ordering": ["-updated_at"]},),
    ]
