# Generated by Django 3.1.5 on 2021-03-05 23:38

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("show", "0001_initial"),
        ("lst", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lst",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddField(
            model_name="lst",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="LstSaveActivity",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lst",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        to="lst.lst",
                    ),
                ),
                (
                    "saved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        to="user.profile",
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        to="show.show",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("lst", "show")},
            },
        ),
    ]
