# Generated by Django 3.1.5 on 2021-03-05 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lst", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="lstsaveactivity", old_name="owner", new_name="saved_by"),
    ]
