# Generated by Django 3.1.5 on 2021-03-05 00:06

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
        ("vote", "0001_initial"),
        ("show", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=30, null=True)),
                ("members", models.ManyToManyField(blank=True, related_name="groups", to="user.Profile")),
                ("shows", models.ManyToManyField(blank=True, to="show.Show")),
                ("votes", models.ManyToManyField(blank=True, to="vote.Vote")),
            ],
        ),
    ]
