# Generated by Django 3.2.11 on 2022-02-18 01:52

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("season_detail", "0001_initial"),
        ("episode_detail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="episodedetail",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="episode_details",
                to="season_detail.seasondetail",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="episodedetail",
            unique_together={("season", "episode_num")},
        ),
    ]
