# Generated by Django 3.1.5 on 2022-03-11 00:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("episode_detail", "0003_auto_20220311_0045"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episodedetail", name="episode_num", field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
