# Generated by Django 3.1.5 on 2021-02-22 22:34

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lst", "0001_initial"),
        ("show", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoverRecommendation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "recommend_type",
                    models.CharField(
                        choices=[
                            ("friend_list", "Friend List"),
                            ("friend_show", "Friend Show"),
                            ("trending_list", "Trending List"),
                            ("trending_show", "Trending Show"),
                        ],
                        default=None,
                        max_length=50,
                    ),
                ),
                (
                    "lst",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation",
                        to="lst.lst",
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation",
                        to="show.show",
                    ),
                ),
            ],
            options={"unique_together": {("recommend_type", "lst", "show")}},
        ),
    ]
