# Generated by Django 3.0.6 on 2021-02-20 22:07

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lst", "0002_lst_num_likes"),
        ("show", "0002_auto_20210220_2158"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoverRecommendation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "recommend_type",
                    models.CharField(
                        choices=[
                            ("friend_list", "Friend List"),
                            ("friend_show", "Friend Show"),
                            ("trending_list", "Trending List"),
                            ("trending_show", "Trending Show"),
                        ],
                        default=None,
                        max_length=50,
                    ),
                ),
                (
                    "lst",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation",
                        to="lst.Lst",
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation",
                        to="show.Show",
                    ),
                ),
            ],
        ),
    ]
