# Generated by Django 3.1.5 on 2021-02-22 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lst", "0002_lst_num_likes"),
        ("show", "0002_auto_20210220_2158"),
        ("discover_recommend", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="discoverrecommendation", unique_together={("recommend_type", "lst", "show")},
        ),
    ]
