# Generated by Django 3.0.6 on 2020-05-31 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("asset", "0002_asset_is_processing"),
        ("lst", "0003_auto_20200531_0103"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("consumer", "Consumer"), ("staff", "Staff")], default="consumer", max_length=8
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("phone_number", models.TextField(blank=True, null=True)),
                ("social_id_token_type", models.TextField(blank=True, null=True)),
                ("social_id_token", models.TextField(blank=True, null=True)),
                ("collab_lsts", models.ManyToManyField(blank=True, related_name="collab_lsts", to="lst.Lst")),
                ("owner_lsts", models.ManyToManyField(blank=True, related_name="owner_lsts", to="lst.Lst")),
                (
                    "profile_pic",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="asset.AssetBundle"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        )
    ]
