# Generated by Django 3.0.6 on 2020-07-11 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("asset", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("consumer", "Consumer"), ("staff", "Staff")], default="consumer", max_length=8
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("profile_pic", models.TextField(blank=True, null=True)),
                ("phone_number", models.TextField(blank=True, null=True)),
                ("social_id_token_type", models.TextField(blank=True, null=True)),
                ("social_id_token", models.TextField(blank=True, null=True)),
                (
                    "profile_asset_bundle",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="asset.AssetBundle"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        )
    ]
