# Generated by Django 3.0.6 on 2021-01-10 03:42

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="notif_time_viewed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
