# Generated by Django 3.0.6 on 2020-05-31 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("asset", "0002_asset_is_processing"), ("user", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="asset.AssetBundle"
            ),
        )
    ]
