# Generated by Django 3.0.6 on 2020-07-25 19:15

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("rating", "0001_initial"), ("user", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="profile", name="ratings", field=models.ManyToManyField(blank=True, to="rating.Rating")
        )
    ]
