# Generated by Django 3.0.6 on 2020-06-01 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("asset", "0002_asset_is_processing"), ("user", "0002_auto_20200531_0138")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_asset_bundle",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="asset.AssetBundle"
            ),
        ),
        migrations.AlterField(model_name="profile", name="profile_pic", field=models.TextField(blank=True, null=True)),
    ]
