# Generated by Django 3.0.6 on 2020-07-25 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("user", "0002_profile_ratings")]

    operations = [migrations.RemoveField(model_name="profile", name="ratings")]
