# Generated by Django 3.0.6 on 2020-06-21 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("user", "0003_auto_20200601_0437")]

    operations = [
        migrations.RemoveField(model_name="profile", name="collab_lsts"),
        migrations.RemoveField(model_name="profile", name="owner_lsts"),
    ]
