# Generated by Django 3.0.6 on 2020-08-30 22:12

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("user", "0003_remove_profile_ratings")]

    operations = [
        migrations.AddField(model_name="profile", name="social_id", field=models.TextField(blank=True, null=True))
    ]
