# Generated by Django 3.0.6 on 2020-06-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("lst", "0004_auto_20200621_2340"), ("user", "0004_auto_20200621_2340")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="collab_lsts",
            field=models.ManyToManyField(blank=True, related_name="collab_lsts", to="lst.Lst"),
        ),
        migrations.AddField(
            model_name="profile",
            name="owner_lsts",
            field=models.ManyToManyField(blank=True, related_name="owner_lsts", to="lst.Lst"),
        ),
    ]
