# Generated by Django 3.0.6 on 2020-06-27 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("user", "0005_auto_20200621_2346")]

    operations = [
        migrations.RemoveField(model_name="profile", name="collab_lsts"),
        migrations.RemoveField(model_name="profile", name="owner_lsts"),
    ]
