# Generated by Django 3.0.6 on 2020-05-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickaccount',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
