# Generated by Django 3.0.6 on 2020-05-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickaccount', '0002_auto_20200520_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickaccount',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='flickaccount',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
