# Generated by Django 3.2.11 on 2022-02-18 01:52

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("show", "0003_show_image_keys"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeasonDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("season_num", models.IntegerField(blank=True, null=True)),
                ("episode_count", models.IntegerField(blank=True, null=True)),
                ("ext_api_id", models.IntegerField(blank=True, null=True)),
                ("poster_pic", models.URLField(blank=True, null=True)),
                ("overview", models.TextField(blank=True, null=True)),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="season_details", to="show.show"
                    ),
                ),
            ],
            options={
                "unique_together": {("show", "season_num")},
            },
        ),
    ]
