# Generated by Django 3.2.11 on 2022-03-29 20:36

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("season_detail", "0003_auto_20220311_0059"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seasondetail",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
