# Generated by Django 3.0.6 on 2020-05-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("tag", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Show",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("poster_pic", models.URLField()),
                ("director", models.CharField(max_length=100)),
                ("is_tv", models.BooleanField()),
                ("date_released", models.DateTimeField()),
                ("status", models.CharField(max_length=100)),
                ("language", models.CharField(max_length=100)),
                ("duration", models.DurationField()),
                ("plot", models.TextField()),
                ("seasons", models.IntegerField()),
                ("audience_level", models.CharField(max_length=100)),
                ("imdb_rating", models.CharField(max_length=10)),
                ("tomato_rating", models.CharField(max_length=10)),
                ("friends_rating", models.IntegerField()),
                ("platforms", models.CharField(max_length=100)),
                ("keywords", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tags", models.ManyToManyField(to="tag.Tag")),
            ],
        )
    ]
