# Generated by Django 3.0.6 on 2021-01-07 05:25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0001_initial"),
        ("show", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="providers",
            field=models.ManyToManyField(blank=True, to="provider.Provider"),
        ),
    ]
