# Generated by Django 3.0.6 on 2021-01-10 07:58

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("show", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="last_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
