# Generated by Django 3.0.6 on 2020-07-25 19:30

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("rating", "0002_auto_20200725_1930"), ("show", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="show", name="ratings", field=models.ManyToManyField(blank=True, to="rating.Rating")
        )
    ]
