# Generated by Django 3.0.6 on 2020-05-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("show", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="show", name="ext_api_id", field=models.IntegerField(default=None), preserve_default=False
        ),
        migrations.AddField(
            model_name="show",
            name="ext_api_source",
            field=models.CharField(choices=[("tmdb", "TMDB"), ("animelist", "Animelist")], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
