# Generated by Django 3.0.6 on 2020-05-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tag", "0002_auto_20200531_0040"), ("show", "0002_auto_20200531_0027")]

    operations = [
        migrations.RemoveField(model_name="show", name="friends_rating"),
        migrations.AlterField(
            model_name="show", name="audience_level", field=models.CharField(blank=True, max_length=100, null=True)
        ),
        migrations.AlterField(model_name="show", name="date_released", field=models.DateField()),
        migrations.AlterField(model_name="show", name="duration", field=models.DurationField(blank=True, null=True)),
        migrations.AlterField(model_name="show", name="ext_api_id", field=models.IntegerField(blank=True, null=True)),
        migrations.AlterField(
            model_name="show",
            name="ext_api_source",
            field=models.CharField(choices=[("tmdb", "TMDB"), ("animelist", "Animelist")], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name="show", name="imdb_rating", field=models.CharField(blank=True, max_length=10, null=True)
        ),
        migrations.AlterField(model_name="show", name="keywords", field=models.TextField(blank=True, null=True)),
        migrations.AlterField(
            model_name="show", name="language", field=models.CharField(blank=True, max_length=100, null=True)
        ),
        migrations.AlterField(
            model_name="show", name="platforms", field=models.CharField(blank=True, max_length=100, null=True)
        ),
        migrations.AlterField(model_name="show", name="poster_pic", field=models.URLField(blank=True, null=True)),
        migrations.AlterField(model_name="show", name="seasons", field=models.IntegerField(blank=True, null=True)),
        migrations.AlterField(
            model_name="show", name="status", field=models.CharField(blank=True, max_length=100, null=True)
        ),
        migrations.AlterField(
            model_name="show", name="tags", field=models.ManyToManyField(blank=True, null=True, to="tag.Tag")
        ),
        migrations.AlterField(
            model_name="show", name="tomato_rating", field=models.CharField(blank=True, max_length=10, null=True)
        ),
    ]
