# Generated by Django 3.0.6 on 2021-01-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("show", "0002_show_last_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="show",
            name="last_updated",
        ),
    ]
