# Generated by Django 3.0.6 on 2021-01-07 23:41

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("show", "0002_show_providers"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="backdrop_pic",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="show",
            name="is_adult",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
