# Generated by Django 3.0.6 on 2020-08-02 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("show", "0002_show_ratings")]

    operations = [
        migrations.AlterUniqueTogether(name="show", unique_together={("title", "ext_api_id", "ext_api_source")})
    ]
