# Generated by Django 3.0.6 on 2020-06-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0002_auto_20200531_0040"),
        ("show", "0003_auto_20200531_0040"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show", name="date_released", field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(model_name="show", name="plot", field=models.TextField(blank=True, null=True),),
        migrations.AlterField(
            model_name="show",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="shows", to="tag.Tag"),
        ),
        migrations.AlterUniqueTogether(
            name="show", unique_together={("title", "ext_api_id", "ext_api_source", "poster_pic", "date_released")},
        ),
    ]
