# Generated by Django 3.0.6 on 2021-01-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("show", "0003_remove_show_last_updated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="show",
            name="audience_level",
        ),
    ]
