# Generated by Django 3.0.6 on 2021-01-07 23:45

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("show", "0003_auto_20210107_2341"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="is_adult",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
