# Generated by Django 3.0.6 on 2020-08-02 07:08

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("show", "0003_auto_20200802_0637")]

    operations = [
        migrations.AlterField(
            model_name="show", name="cast", field=models.CharField(blank=True, max_length=200, null=True)
        ),
        migrations.AlterField(
            model_name="show", name="directors", field=models.CharField(blank=True, max_length=100, null=True)
        ),
    ]
