# Generated by Django 3.0.6 on 2020-05-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tag", "0002_auto_20200531_0040"), ("show", "0003_auto_20200531_0040")]

    operations = [
        migrations.AlterField(model_name="show", name="tags", field=models.ManyToManyField(blank=True, to="tag.Tag"))
    ]
