# Generated by Django 3.0.6 on 2021-01-17 04:37

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("show", "0004_remove_show_audience_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="animelist_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="show",
            name="episodes",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
