# Generated by Django 3.0.6 on 2020-06-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("show", "0004_auto_20200531_0103")]

    operations = [
        migrations.AlterField(model_name="show", name="date_released", field=models.DateField(blank=True, null=True))
    ]
