# Generated by Django 3.0.6 on 2021-01-08 05:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("show", "0004_auto_20210107_2345"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="duration",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
