# Generated by Django 3.0.6 on 2020-06-13 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("show", "0005_auto_20200613_2228")]

    operations = [migrations.AlterUniqueTogether(name="show", unique_together={("ext_api_id", "ext_api_source")})]
