# Generated by Django 3.0.6 on 2021-01-08 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("show", "0005_auto_20210108_0531"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="show",
            name="platforms",
        ),
    ]
