# Generated by Django 3.0.6 on 2021-01-17 05:58

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("show", "0005_auto_20210117_0437"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="animelist_rank",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
