# Generated by Django 3.0.6 on 2020-06-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tag", "0002_auto_20200531_0040"), ("show", "0006_auto_20200613_2330")]

    operations = [
        migrations.AlterField(
            model_name="show", name="tags", field=models.ManyToManyField(blank=True, related_name="shows", to="tag.Tag")
        )
    ]
