# Generated by Django 3.0.6 on 2020-08-20 00:10

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("show", "0006_auto_20200802_0723")]

    operations = [
        migrations.AlterField(model_name="show", name="imdb_rating", field=models.IntegerField(blank=True, null=True))
    ]
