# Generated by Django 3.0.6 on 2020-06-14 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("show", "0007_auto_20200614_0105")]

    operations = [
        migrations.AlterUniqueTogether(
            name="show", unique_together={("title", "ext_api_id", "ext_api_source", "poster_pic")}
        )
    ]
