# Generated by Django 3.0.6 on 2020-06-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("show", "0008_auto_20200614_1938")]

    operations = [
        migrations.AlterField(
            model_name="show", name="date_released", field=models.CharField(blank=True, max_length=100, null=True)
        ),
        migrations.AlterField(model_name="show", name="plot", field=models.TextField(blank=True, null=True)),
    ]
