# Generated by Django 3.0.6 on 2020-06-15 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("show", "0009_auto_20200615_0247")]

    operations = [
        migrations.AlterUniqueTogether(
            name="show", unique_together={("title", "ext_api_id", "ext_api_source", "poster_pic", "date_released")}
        )
    ]
