# Generated by Django 3.0.6 on 2020-06-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("show", "0004_auto_20200627_1805"),
        ("show", "0010_auto_20200615_0252"),
    ]

    operations = []
