# Generated by Django 3.0.6 on 2020-06-28 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("show", "0011_merge_20200627_1814"),
    ]

    operations = [
        migrations.RenameField(model_name="show", old_name="director", new_name="directors",),
    ]
