# Generated by Django 3.0.6 on 2020-06-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("show", "0012_auto_20200628_0223"),
    ]

    operations = [
        migrations.AddField(model_name="show", name="cast", field=models.CharField(max_length=200, null=True),),
    ]
