# Generated by Django 3.0.6 on 2021-01-07 05:25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("image", models.URLField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("name", "image")},
            },
        ),
    ]
