# Generated by Django 3.0.6 on 2020-05-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tag", "0001_initial")]

    operations = [
        migrations.AlterField(model_name="tag", name="tag", field=models.CharField(max_length=100, unique=True))
    ]
