# Generated by Django 3.0.7 on 2020-07-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='ext_api_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='ext_api_source',
            field=models.CharField(choices=[('tmdb', 'TMDB'), ('animelist', 'Animelist')], max_length=20, null=True),
        ),
    ]
