# Generated by Django 3.0.6 on 2020-08-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("tag", "0002_auto_20200718_0237")]

    operations = [
        migrations.RenameField(model_name="tag", old_name="ext_api_id", new_name="ext_api_genre_id"),
        migrations.RenameField(model_name="tag", old_name="tag", new_name="name"),
    ]
