# Generated by Django 3.0.6 on 2020-08-11 05:36

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("tag", "0003_auto_20200802_1954")]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="ext_api_source",
            field=models.CharField(
                blank=True, choices=[("tmdb", "TMDB"), ("animelist", "Animelist")], max_length=20, null=True
            ),
        )
    ]
