# Generated by Django 3.1.5 on 2021-03-06 02:43

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rating", "0001_initial"),
        ("tag", "0001_initial"),
        ("provider", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Show",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.TextField()),
                ("ext_api_id", models.IntegerField(blank=True, null=True)),
                (
                    "ext_api_source",
                    models.CharField(
                        choices=[("tmdb", "TMDB"), ("animelist", "Animelist")], default=None, max_length=20
                    ),
                ),
                ("poster_pic", models.URLField(blank=True, null=True)),
                ("backdrop_pic", models.URLField(blank=True, null=True)),
                ("directors", models.TextField(blank=True, null=True)),
                ("cast", models.TextField(blank=True, null=True)),
                ("is_tv", models.BooleanField()),
                ("is_adult", models.BooleanField(blank=True, null=True)),
                ("date_released", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("language", models.TextField(blank=True, null=True)),
                ("duration", models.TextField(blank=True, null=True)),
                ("plot", models.TextField(blank=True, null=True)),
                ("seasons", models.IntegerField(blank=True, null=True)),
                ("episodes", models.IntegerField(blank=True, null=True)),
                ("imdb_rating", models.IntegerField(blank=True, null=True)),
                ("tomato_rating", models.CharField(blank=True, max_length=10, null=True)),
                ("animelist_rating", models.IntegerField(blank=True, null=True)),
                ("animelist_rank", models.IntegerField(blank=True, null=True)),
                ("keywords", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("providers", models.ManyToManyField(blank=True, to="provider.Provider")),
                ("ratings", models.ManyToManyField(blank=True, to="rating.Rating")),
                ("tags", models.ManyToManyField(blank=True, related_name="shows", to="tag.Tag")),
            ],
            options={
                "unique_together": {("title", "ext_api_id", "ext_api_source", "poster_pic")},
            },
        ),
    ]
