# Generated by Django 3.0.6 on 2021-02-20 21:58

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("show", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(model_name="show", name="cast", field=models.TextField(blank=True, null=True),),
        migrations.AlterField(model_name="show", name="date_released", field=models.TextField(blank=True, null=True),),
        migrations.AlterField(model_name="show", name="directors", field=models.TextField(blank=True, null=True),),
        migrations.AlterField(model_name="show", name="duration", field=models.TextField(blank=True, null=True),),
        migrations.AlterField(model_name="show", name="language", field=models.TextField(blank=True, null=True),),
        migrations.AlterField(model_name="show", name="status", field=models.TextField(blank=True, null=True),),
        migrations.AlterField(model_name="show", name="title", field=models.TextField(),),
    ]
