# Generated by Django 3.0.6 on 2021-05-08 07:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("show", "0002_show_trailer_keys"),
    ]

    operations = [
        migrations.AddField(model_name="show", name="image_keys", field=models.TextField(blank=True, null=True),),
    ]
