name: Production Docker Build & Push and Deploy

on:
    push:
        branches: [master]
jobs:
    path-context:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Get SHA
              id: vars
              run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
            - name: Docker build & push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/app:${{ steps.vars.outputs.sha_short }}
            - name: Remote ssh and deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DO_PROD_SERVER_HOST }}
                  username: ${{ secrets.DO_SERVER_USERNAME }}
                  key: ${{ secrets.DO_SERVER_KEY }}
                  script: |
                      export IMAGE_TAG=${{ steps.vars.outputs.sha_short }}
                      cd docker-compose
                      docker stack rm the-stack
                      sleep 20s
                      docker stack deploy -c docker-compose.yml the-stack
                      yes | docker system prune -a
